# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89df02566665df437d2fa283e106dbeaa03d6a57ac57d51b3d25cc04bdbeb4792ecc21f4dce0e1861bb42667fe96089816fc5863d7d957a66ffa9f6d3ecbe1e3

test:
  secret_key_base: 094b601f95ccedea65c892e7332409affa5c29fc7ac2af2b44343966a93c5887863261528f41d876f3413adf18806283e3a0f7f0ef28e17addebc32f086ff7ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
